#!/usr/bin/env python3
"""Turn raylib.toml into the CMake inputs.

Runs on every configure, from cmake/configure_hook.cmake, so `cmake --preset
debug` is the only command you ever type after editing the config. It writes
CMake files and nothing else — there is no generated header, because the window
and its title are arguments to InitWindow() and belong in your code. It takes
milliseconds and rewrites a file only when its content actually changed, so
nothing rebuilds for no reason.

  python3 tools/configure.py              generate
  python3 tools/configure.py --check      validate without writing
  python3 tools/configure.py --print-name print the project name (the Justfile
                                          uses this so `just run` follows a rename)

Needs Python 3.11 or newer, for tomllib.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "raylib.toml"
GEN = REPO / "cmake" / "generated"
HEADER = "GENERATED by tools/configure.py from raylib.toml — do not edit."


class ConfigError(Exception):
    pass


DEFAULTS: dict = {
    "project": {"name": "game"},
    "raylib": {"disabled_modules": []},
    "windows": {"backend": "glfw"},
    "linux": {"backend": "glfw", "wayland": False},
    "dev": {"compiler": "default", "linker": "auto"},
}

# raylib's own SUPPORT_* options are deliberately not used: they only take
# effect with CUSTOMIZE_BUILD=ON, and turning that on flips roughly fifteen
# flags that are 0 in config.h to ON, because raylib's ParseConfigHeader.cmake
# maps any uncommented #define to ON without reading its value. Supplying the
# complete set through EXTERNAL_CONFIG_FLAGS is the only way to get what the
# config actually asked for.
OPTIONAL_MODULES = {"rshapes", "rtextures", "rtext", "rmodels", "raudio"}
COMPILERS = {"clang", "gcc", "mingw", "msvc", "default"}
WINDOWS_BACKENDS = {"glfw", "win32", "rgfw"}
LINUX_BACKENDS = {"glfw", "rgfw"}
LINKERS = {"auto", "mold", "lld", "default"}


def deep_merge(base: dict, over: dict) -> dict:
    out = dict(base)
    for key, value in over.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def load_config() -> dict:
    if not CONFIG.is_file():
        print(f"warning: {CONFIG.name} not found; using defaults", file=sys.stderr)
        return DEFAULTS
    try:
        with CONFIG.open("rb") as handle:
            user = tomllib.load(handle)
    except tomllib.TOMLDecodeError as exc:
        raise ConfigError(f"{CONFIG.name} is not valid TOML: {exc}") from exc
    return deep_merge(DEFAULTS, user)


def validate(cfg: dict) -> None:
    name = cfg["project"]["name"]
    if not re.fullmatch(r"[A-Za-z0-9_-]+", str(name)):
        raise ConfigError(
            f"[project] name = {name!r} becomes a filename on three operating "
            "systems. Use letters, digits, '_' and '-' only."
        )

    unknown = set(cfg["raylib"]["disabled_modules"]) - OPTIONAL_MODULES
    if unknown:
        raise ConfigError(
            f"[raylib] disabled_modules: {sorted(unknown)} is not a module that can be "
            f"disabled. Pick from {sorted(OPTIONAL_MODULES)} — rcore and rlgl are mandatory."
        )

    if cfg["windows"]["backend"] not in WINDOWS_BACKENDS:
        raise ConfigError(f"[windows] backend has to be one of {sorted(WINDOWS_BACKENDS)}")
    if cfg["linux"]["backend"] not in LINUX_BACKENDS:
        raise ConfigError(f"[linux] backend has to be one of {sorted(LINUX_BACKENDS)}")
    if not isinstance(cfg["linux"]["wayland"], bool):
        raise ConfigError("[linux] wayland has to be true or false")
    # Individually valid, together a contradiction: RGFW's Linux backend is
    # X11-only, so the build would quietly produce X11 while the config said
    # Wayland. Better a message here than a surprise later.
    if cfg["linux"]["backend"] == "rgfw" and cfg["linux"]["wayland"]:
        raise ConfigError(
            '[linux] backend = "rgfw" and wayland = true cannot both hold: RGFW on Linux '
            'is X11-only.\nPick backend = "glfw" for native Wayland, or wayland = false.')

    if cfg["dev"]["compiler"] not in COMPILERS:
        raise ConfigError(f"[dev] compiler has to be one of {sorted(COMPILERS)}")
    if cfg["dev"]["linker"] not in LINKERS:
        raise ConfigError(f"[dev] linker has to be one of {sorted(LINKERS)}")


def write(path: Path, content: str) -> bool:
    """Write only if the content changed, so nothing rebuilds spuriously."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def cmake_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def gen_project(cfg: dict) -> bool:
    name = cfg["project"]["name"]
    return write(GEN / "project.cmake", f"""# {HEADER}
set(TEMPLATE_PROJECT_NAME "{cmake_escape(name)}")
set(TEMPLATE_WINDOWS_BACKEND "{cfg["windows"]["backend"]}")
set(TEMPLATE_LINUX_BACKEND "{cfg["linux"]["backend"]}")
set(TEMPLATE_LINUX_WAYLAND {"ON" if cfg["linux"]["wayland"] else "OFF"})
""")


def parse_raylib_config() -> dict[str, int]:
    """Read every flag and its real value out of raylib's config.h.

    Defining EXTERNAL_CONFIG_FLAGS skips config.h's ENTIRE default block, not
    just the module switches, so the complete set has to be supplied back or a
    flag we drop becomes undefined — and `#if SUPPORT_X` treats undefined as 0,
    silently turning off something nobody asked to turn off. Hence the checks.
    """
    header = REPO / "thirdparty" / "raylib" / "src" / "config.h"
    if not header.is_file():
        raise ConfigError(f"{header} not found (is thirdparty/raylib checked out?)")

    text = header.read_text(encoding="utf-8", errors="replace")
    start = text.find("#if !defined(EXTERNAL_CONFIG_FLAGS)")
    end = text.find("#endif // !EXTERNAL_CONFIG_FLAGS")
    if start < 0 or end < 0:
        raise ConfigError(
            "could not find the EXTERNAL_CONFIG_FLAGS guard in raylib's config.h. "
            "raylib's layout changed; tools/configure.py needs updating.")

    flags: dict[str, int] = {}
    unrepresentable: list[str] = []
    for line in text[start:end].splitlines():
        stripped = line.strip()
        if stripped.startswith("//") or not stripped.startswith("#define"):
            continue  # commented out: raylib's own sources supply the default
        match = re.match(r"#define\s+([A-Za-z_]\w*)\s+(-?\d+)\s*(//.*)?$", stripped)
        if match:
            flags[match.group(1)] = int(match.group(2))
            continue
        named = re.match(r"#define\s+([A-Za-z_]\w*)", stripped)
        unrepresentable.append(named.group(1) if named else stripped)

    if unrepresentable:
        raise ConfigError(
            "raylib's config.h defines values inside the EXTERNAL_CONFIG_FLAGS guard that this "
            "generator cannot carry over as integers:\n  " + ", ".join(unrepresentable) +
            "\nUpdate tools/configure.py to pass them through, or they get silently lost.")

    for module in OPTIONAL_MODULES:
        required = f"SUPPORT_MODULE_{module.upper()}"
        if required not in flags:
            raise ConfigError(f"{required} not found in raylib's config.h — "
                              "raylib's layout changed; tools/configure.py needs updating.")
    return flags


def gen_raylib_flags(cfg: dict) -> bool:
    flags = parse_raylib_config()
    for module in cfg["raylib"]["disabled_modules"]:
        flags[f"SUPPORT_MODULE_{module.upper()}"] = 0

    body = "\n".join(f"  {name}={value}" for name, value in sorted(flags.items()))
    disabled = cfg["raylib"]["disabled_modules"]
    note = ", ".join(sorted(disabled)) if disabled else "none"
    return write(GEN / "raylib_flags.cmake", f"""# {HEADER}
# The COMPLETE set of raylib's config flags, read out of its own config.h with
# the modules from [raylib] disabled_modules set to 0. Disabled here: {note}.
#
# EXTERNAL_CONFIG_FLAGS makes raylib skip its own defaults, which is why the
# whole set is repeated rather than just the differences.
set(RAYLIB_CONFIG_DEFS
  EXTERNAL_CONFIG_FLAGS
{body}
)
""")


def gen_dev_toolchain(cfg: dict) -> bool:
    compiler = cfg["dev"]["compiler"]
    linker = cfg["dev"]["linker"]
    lines = [f"# {HEADER}",
             "# Development builds only. Included before project(), which is where CMake",
             "# locks the compiler in."]

    if compiler != "default":
        # Several names per compiler, because which one works depends on how it
        # was installed. MinGW is almost never plain `gcc` on Windows: MSYS2
        # ships x86_64-w64-mingw32-gcc, and picking up a stray `gcc` from a
        # Git-for-Windows shell is how you get a build that asks for X11.
        names = {
            "clang": (["clang"], ["clang++"]),
            "gcc":   (["gcc"], ["g++"]),
            "mingw": (["x86_64-w64-mingw32-gcc", "gcc"], ["x86_64-w64-mingw32-g++", "g++"]),
            "msvc":  (["cl"], ["cl"]),
        }[compiler]
        if compiler in ("mingw", "msvc"):
            # A Linux box with the mingw cross-compiler installed would
            # otherwise find it and quietly start producing .exe files.
            lines += ['if(NOT WIN32)',
                      f'  message(FATAL_ERROR "[dev] compiler = {compiler} only makes sense '
                      'on Windows. Here, use clang, gcc or default.")',
                      'endif()']
        lines += [f'find_program(_dev_cc  NAMES {" ".join(names[0])})',
                  f'find_program(_dev_cxx NAMES {" ".join(names[1])})',
                  'if(_dev_cc AND _dev_cxx)',
                  '  set(CMAKE_C_COMPILER   "${_dev_cc}"  CACHE FILEPATH "" FORCE)',
                  '  set(CMAKE_CXX_COMPILER "${_dev_cxx}" CACHE FILEPATH "" FORCE)',
                  'endif()']

    if linker in ("auto", "mold", "lld"):
        wanted = ["mold", "lld"] if linker == "auto" else [linker]
        lines.append(f'foreach(_ld {" ".join(wanted)})')
        lines += ['  find_program(_dev_ld NAMES ${_ld})',
                  '  if(_dev_ld)',
                  '    add_link_options("-fuse-ld=${_ld}")',
                  '    break()',
                  '  endif()',
                  'endforeach()']
    return write(GEN / "dev_toolchain.cmake", "\n".join(lines) + "\n")


def main(argv: list[str]) -> int:
    try:
        cfg = load_config()
        validate(cfg)
    except ConfigError as exc:
        print(f"FALLA: {exc}", file=sys.stderr)
        return 1

    if "--print-name" in argv:
        print(cfg["project"]["name"])
        return 0
    if "--check" in argv:
        print(f"  ok    {CONFIG.name} is valid")
        return 0

    changed = [gen_project(cfg), gen_raylib_flags(cfg), gen_dev_toolchain(cfg)]
    if any(changed):
        print(f"configuration regenerated from {CONFIG.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
