name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  PROJECT_NAME: ray_test

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Zip windows build
        run: |
         Compress-Archive -Path build/${{ env.PROJECT_NAME }}.exe -DestinationPath windows-build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-build
          path: windows-build.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgl1-mesa-dev \
            libx11-dev libxrandr-dev libxi-dev \
            libxinerama-dev libxcursor-dev

      - name: Configure
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Zip linux build
        run: |
         zip linux-build.zip build/${{ env.PROJECT_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: linux-build
          path: linux-build.zip

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset release

      - name: Zip mac build
        run: |
         zip mac-build.zip build/${{ env.PROJECT_NAME }}

      - name: Build
        run: cmake --build --preset release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: mac-build
          path: mac-build.zip

  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install Ninja
      run: sudo apt install -y ninja-build

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v16
      with:
        version: latest

    - name: Configure
      run: cmake --preset web

    - name: Build
      run: cmake --build --preset web

    - name: Zip web build
      run: |
       cd build/web
       zip -r ../../web-build.zip ${{ env.PROJECT_NAME }}.html ${{ env.PROJECT_NAME }}.js ${{ env.PROJECT_NAME }}.wasm ${{ env.PROJECT_NAME }}.data

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: web-build
        path: |
          web-build.zip

  release:
    needs: [build-windows, build-linux, build-mac, build-web]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
     contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v6

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
           linux-build/linux-build.zip
           mac-build/mac-build.zip
           web-build/web-build.zip
