name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  PROJECT_NAME: ray_test

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-build
          path: build/${{ env.PROJECT_NAME }}.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgl1-mesa-dev \
            libx11-dev libxrandr-dev libxi-dev \
            libxinerama-dev libxcursor-dev

      - name: Configure
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: linux-build
          path: build/${{ env.PROJECT_NAME }}

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: mac-build
          path: build/${{ env.PROJECT_NAME }}

  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install Ninja
      run: sudo apt install -y ninja-build

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v16
      with:
        version: latest

    - name: Configure
      run: cmake --preset web

    - name: Build
      run: cmake --build --preset web

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: web-build
        path: |
          build/web/${{ env.PROJECT_NAME }}.html
          build/web/${{ env.PROJECT_NAME }}.js
          build/web/${{ env.PROJECT_NAME }}.wasm
          build/web/${{ env.PROJECT_NAME }}.data

  release:
    needs: [build-windows, build-linux, build-mac, build-web]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
     contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v6

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-build/${{ env.PROJECT_NAME }}.exe
            linux-build/${{ env.PROJECT_NAME }}
            mac-build/${{ env.PROJECT_NAME }}
            web-build/${{ env.PROJECT_NAME }}.html
            web-build/${{ env.PROJECT_NAME }}.js
            web-build/${{ env.PROJECT_NAME }}.wasm
            web-build/${{ env.PROJECT_NAME }}.data
